FROM python:alpine3.19

WORKDIR /app

COPY requirments-backend.txt /app/requirements.txt

RUN pip install --upgrade pip && pip install --no-cache-dir --upgrade -r /app/requirements-frontend.txt

COPY ./web /app/src

EXPOSE 80

CMD [ "python3" "./src/main.py" ]
