FROM python:alpine3.19

WORKDIR /raspiProjekt

COPY docker/requirments-backend.txt /raspiProjekt/requirments.txt

# RUN pip install -r /raspiProjekt/requirments.txt
RUN pip install --no-chache fastapi
RUN pip install --no-chache pydantic
RUN pip install --no-chache uvicorn
RUN pip install --no-chache RPi.GPIO
RUN pip install --no-chache board
RUN pip install --no-chache adafruit_bmp280

COPY ./src /raspiProjekt/src

EXPOSE 8000

CMD [ "uvicorn", "src.api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
