FROM python:alpine3.19

WORKDIR /app

COPY docker/requirments-backend.txt /app/requirments.txt

RUN pip install --no-chache --update -r /app/requirments-frontend.txt

COPY ./web /app/src

EXPOSE 80

CMD [ "python3" "./src/main.py" ]
