FROM python:alpine3.19

WORKDIR /raspiProjekt

COPY docker/requirments-backend.txt /raspiProjekt/requirements.txt

RUN pip install --no-cache-dir -r /raspiProjekt/requirements-backend.txt

COPY ./src /raspiProjekt/src

EXPOSE 8000

CMD [ "uvicorn", "src.api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
