FROM python:alpine3.19

WORKDIR /app

COPY docker/requirments-backend.txt /app/requirments.txt

RUN apt-get update && apt-get upgrade -y && pip install --no-chache -r /app/requirments.txt

COPY ./web /app/src

EXPOSE 80

CMD [ "python3" "./src/main.py" ]
