name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get repository name in lowercase
        id: lowercase
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY,,})"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://raspi.debian.net/tested/20231109_raspi_4_bookworm.img.xz
          commands: |
              apt-get update && \
              apt-get -y upgrade && \
              apt-get install ca-certificates curl gnupg && \
              install -m 0755 -d /etc/apt/keyrings && \
              curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
              chmod a+r /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              tee /etc/apt/sources.list.d/docker.list > /dev/null && \
              apt-get update && \
              apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
              docker build --compress --no-cache --file /docker/Dockerfile-backend --tag ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors-backend:latest && \
              docker push ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get repository name in lowercase
        id: lowercase
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY,,})"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: https://raspi.debian.net/tested/20231109_raspi_4_bookworm.img.xz
          commands: |
              apt-get update && \
              apt-get -y upgrade && \
              apt-get install ca-certificates curl gnupg && \
              install -m 0755 -d /etc/apt/keyrings && \
              curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
              chmod a+r /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              tee /etc/apt/sources.list.d/docker.list > /dev/null && \
              apt-get update && \
              apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
              docker build --compress --no-cache --file /docker/Dockerfile-frontend --tag ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors-frontend:latest && \
              docker push ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors-frontend:latest
