name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get repository name in lowercase
        id: lowercase
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY,,})"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile-backend
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors:backend

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get repository name in lowercase
        id: lowercase
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY,,})"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile-frontend
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.repo }}-sensors:frontend
