name: Build and Push Docker Images

on:
    workflow_dispatch:

jobs:
    build-and-push-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v2

            - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Packages
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                context: .
                file: docker/Dockerfile-backend
                platforms: linux/arm/v7
                push: true
                tags: ghcr.io/${{ github.repository }}/sensors:backend

    build-and-push-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v2

            - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Packages
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                context: .
                file: docker/Dockerfile-frontend
                platforms: linux/arm/v7
                push: true
                tags: ghcr.io/${{ github.repository }}/sensors:frontend
